### ISSUE TITLE
Login / register 

### ISSUE THREAD

**Issue by RowinRuizendaal** [RowinRuizendaal/Bloom#2]
Front-end:

- Log in page
- Register page

Backend:
- Database structure for logging in and registering new users

https://bezkoder.com/vue-node-express-mongodb-mevn-crud/

**Comment by ralfz123** [comment]
# Update

- [x] Setup node.js environment
- [x] Connection successfull to database
- [x] Register a user
- [x] Login with existing emailaddress & password

**Comment by ralfz123** [comment]
# Update 2

Now the backend works, I'm going to try to serve a Vue genrated .html frontend page that can be served by the backend and you can login/register with/an account.

- [x] Render frontend html to client
- [x] Login client
- [x] register client

**Comment by RowinRuizendaal** [comment]
Cool, maybe we should look into the following for next week:

- Storing sessions
- Authorizing routes (if there is a session render the page, if not redirect the user to the login page)
- Salting passwords (bycrypt or any method that seems good)
- Maybe it is cool to use nodemailer to send mails to registered members

For now let's focus on the primary things to show it in the demo for upcoming friday 🔥

**Comment by ralfz123** [comment]
> Cool, maybe we should look into the following for next week:
> 
> * Storing sessions
> * Authorizing routes (if there is a session render the page, if not redirect the user to the login page)
> * Salting passwords (bycrypt or any method that seems good)
> * Maybe it is cool to use nodemailer to send mails to registered members
> 
> For now let's focus on the primary things to show it in the demo for upcoming friday 🔥

Yeah. Salting passwords I surely want to implement, but nodemailer is new for me but also awesome feature. Sessions and auth routes defnitely cool. Think that storing sessions has a priority because of storing data to the session.

**Comment by ralfz123** [comment]
# Update 3

## Styling
- [ ] Every step-component gets the styling of the others. Each component has to have an imported `.scss` file 
- [x] login
- [x] register
- [x] Change stepnames because of missunderstanding concept register
- [x] input component make ready for use in register step 1 (email & pw)

## State
### Components/steps
- Register progressive disclosure (multi-step form) --> vuex Store
     - [x] Switch between components
     - [x] Add state of which step is current
            - [ ]  at pagereload, check state
      - [ ] Bullet points state
### Data
- [x] Add state of data
     - [ ] pass key name with data to vuex store (for dynamic and dry function)
     - [x] Radio take specific value
     - [x] Checkbox: take all checked values
     - [x] Textarea: get value

### Submit
- [x] Submit form data to server when on ready page 
- [x] check if all required inputs are filled with data)

- [x] Create method for recognizing the articles in the surName for the profile avatar.

**Comment by RowinRuizendaal** [comment]
Done? :)

**Comment by ralfz123** [comment]
> Done? :)

Yeah
